project_name: OliveTin
before:
  hooks:
    - go mod tidy
    - make grpc
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm # 32bit
    main: cmd/OliveTin/main.go
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

archives:
  - 
    format: tar.gz

    files: 
      - var/config.yaml
      - README.md
      - Dockerfile
      - webui

    replacements:
      darwin: macOS
      amd64: x86_64

    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

    format_overrides:
      - goos: windows
        format: zip

dockers:
  - dockerfile: Dockerfile

nfpms:
  - maintainer: James Read <contact@jread.com>
    description: OliveTin is a web interface for running Linux shell commands.
    homepage: https://github.com/jamesread/OliveTin
    license: AGPL-3.0
    formats:
      - deb
      - rpm
      - apk
