project_name: OliveTin
before:
  hooks:
    - go mod tidy
    - make grpc
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
    main: cmd/OliveTin/main.go

    # For modern ARM
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - arm64
    main: cmd/OliveTin/main.go

    # For old RPIs
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - arm # 32bit
    main: cmd/OliveTin/main.go

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

archives:
  - 
    format: tar.gz

    files: 
      - var/config.yaml
      - README.md
      - Dockerfile
      - webui

    replacements:
      darwin: macOS

    name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"

    wrap_in_directory: true

    format_overrides:
      - goos: windows
        format: zip

dockers:
  - dockerfile: Dockerfile
    goos: linux
    goarch: amd64
    skip_push: true
    build_flag_templates:
      - "--platform=linux/arm64"

nfpms:
  - maintainer: James Read <contact@jread.com>
    description: OliveTin is a web interface for running Linux shell commands.
    homepage: https://github.com/jamesread/OliveTin
    license: AGPL-3.0
    formats:
      - deb
      - rpm
      - apk
