# The WebUI is simply a static webserver. OliveTin comes with one builtin to
# make things easy, but you can also host the "webui" directory on a static 
# webserver.
listenAddressWebUI: 0.0.0.0:1337 # Listen on all addresses available, port 1337

# The REST API is used by the WebUI. 
#listenAddressRestActions: 0.0.0.0:1338 

# The gRPC API is unsed by the WebUI, and can also be limited to localhost:1339.
#listenAddressGrpcActions: 0.0.0.0:1339 

# Choose from INFO (default), WARN and DEBUG
logLevel: "INFO"

# Actions (buttons) to show up on the WebUI:
actions: 
- title: Restart Plex
  icon: smile
  shell: docker restart plex
  
  # This will send 1 ping (-c 1)
- title: Ping Google.com
  shell: ping google.com -c 1
  icon: ping
  
  # Restart lightdm on host "overseer"
- title: restart lightdm
  icon: poop
  shell: ssh root@overseer 'service lightdm restart'

- title: "teratan.lan Ansible site.yml"
  icon: "&#x1F1E6"
  shell: ansible-playbook -i /etc/hosts /root/myPlaybook.yaml

- title: sleep 2 seconds
  shell: sleep 2
  icon: "&#x1F971"

- title: sleep 5 seconds (timeout)
  shell: sleep 5
  icon: "&#x1F62A"

